name: hello-world

on:
  push:
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize" ]
  check_suite:
    types: [requested]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-step
        run: echo "Hello World!"
